### ISSUE TITLE
Deploy a Concourse Worker on the XPS

### ISSUE THREAD

**Issue by scottmuc** [scottmuc/infrastructure#22]
# Definition of Done

This pipeline should run and work:

```
jobs:
  - name: job-hello-world
    public: true
    plan:
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args: [hello world]
```
